### ISSUE TITLE
Foto perfil - Borda mais fina em cima

### ISSUE THREAD

**Issue by isaaceliape** [mikaelelias/portfolio#4]
<img width="456" alt="Screenshot 2023-08-29 at 09 32 49" src="https://github.com/mikaelelias/portfolio/assets/398091/d9e3e138-a54b-485a-8643-758b8be7b14c">

A borda tá mais fina em cima do que em baixo, eu sugiro adicionar um `padding-top` e um `border-radius: 50%;` pra tentar corrigir.

**Comment by isaaceliape** [comment]
Corrigido

**Comment by mikaelelias** [comment]
Feito.
