### ISSUE TITLE
Container muito grande

### ISSUE THREAD

**Issue by isaaceliape** [mikaelelias/portfolio#5]
### Problema
O container tá expandindo muito quando a resolução da tela é grande (4k).

### Sugestão
Limitar o tamanho do container com `max-width`, de acordo com o layout ele deve ser de no máximo `1204px`.

<img width="2594" alt="Screenshot 2023-08-29 at 09 36 46" src="https://github.com/mikaelelias/portfolio/assets/398091/4f462b86-144e-4cb5-8d9c-ccf623a23594">

**Comment by mikaelelias** [comment]
![image](https://github.com/mikaelelias/portfolio/assets/129218135/b5727210-64d5-422e-b64d-f2881e47f705)

Feito... só estou sentindo uma diferença no header

**Comment by isaaceliape** [comment]
Aplica as mudanças que eu sugeri no Whatsapp dai se funcionar a gente pode fechar essa issue.

**Comment by mikaelelias** [comment]
Aplicado.
