### ISSUE TITLE
Font italica no menu

### ISSUE THREAD

**Issue by isaaceliape** [mikaelelias/portfolio#6]
### Problema
Acho que o import da font "DM Sans" tem algum problema, ele está carregando uma fonte italica ao invez de uma normal.

### Sugestão
Tenta trocar o importe no css pra esse a baixo.
`@import url('https://fonts.googleapis.com/css2?family=DM+Sans:opsz,wght@9..40,300;9..40,400;9..40,500;9..40,700&display=swap');`

### Problema
A cor dos link não está correta.

### Sugestão
Aplicar a cor pra o a tag `<a>` dentro do menu

<img width="809" alt="Screenshot 2023-08-29 at 09 46 26" src="https://github.com/mikaelelias/portfolio/assets/398091/bb4ced33-c4e0-484d-b764-1f8b57ad2091">
<img width="1303" alt="Screenshot 2023-08-29 at 09 48 43" src="https://github.com/mikaelelias/portfolio/assets/398091/9bddacf2-c290-4c11-bce0-5c606bf98fff">

**Comment by mikaelelias** [comment]
Feito 
![image](https://github.com/mikaelelias/portfolio/assets/129218135/161dab10-a9a8-4e7e-9726-f46217fa635d)

**Comment by isaaceliape** [comment]
Perfeito! 👍
