### ISSUE TITLE
Texto faltando efeito de sombra

### ISSUE THREAD

**Issue by isaaceliape** [mikaelelias/portfolio#7]
### Problema
O texto está faltando a propriedade text-shadow.

### Sugestão
Aplicar propriedade de acordo com o layout
<img width="497" alt="Screenshot 2023-08-29 at 09 54 24" src="https://github.com/mikaelelias/portfolio/assets/398091/4e5c3c59-8da7-4daa-93df-18665b87ddc3">
<img width="497" alt="Screenshot 2023-08-29 at 09 54 16" src="https://github.com/mikaelelias/portfolio/assets/398091/3f1a6e27-08f9-46e5-9d65-faa2d326f5f7">

**Comment by mikaelelias** [comment]
Feito!

**Comment by mikaelelias** [comment]
![image](https://github.com/mikaelelias/portfolio/assets/129218135/042934de-f9ef-4a71-b173-fb3b075c0223)

**Comment by isaaceliape** [comment]
Tem duas coisas que ainda estão faltando.
- Sombra no text **.highlight**
- Ajustar o **blur** da sombra, como vc pode ver no exemplo embaixo, a sombra do seu tá sem esfumaçado, vc pode corrigir isso com o seguinte CSS `text-shadow: 0px 4px 4px rgba(0, 0, 0, 0.25);` o terceiro parâmetro (4px) é a que define o esfumaçado

## Layout
<img width="731" alt="Screenshot 2023-08-31 at 11 20 37" src="https://github.com/mikaelelias/portfolio/assets/398091/5749f592-9102-4500-bd43-9b018efad2c6">

## Site programado
<img width="703" alt="Screenshot 2023-08-31 at 11 20 49" src="https://github.com/mikaelelias/portfolio/assets/398091/9624f2ee-e598-4875-b732-6f16ebae3c4d">

**Comment by mikaelelias** [comment]
Sombra é uma parada que não uso muito... vou da uma sacada aqui.

**Comment by mikaelelias** [comment]
Feito.

**Comment by isaaceliape** [comment]
As mudanças não tão aparecendo pra mim, tu deu push?

**Comment by mikaelelias** [comment]
sim!
